os: osx
language: python

node_js:
- 3.6

before_install:
- pip install -r requirements.txt

jobs:
  include:
  - stage: Build App Bundle
    script: setup.py install py2app
  - stage: Compress
    script: cd dist && zip betterles Better\ LES.app
  - stage: Create Relase
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      file: dist/betterles.zip
      draft: true
      on:
        tags: true
