os: osx
language: generic

before_install:
- python3.6 --version
- curl -O https://bootstrap.pypa.io/get-pip.py
- python3 get-pip.py
- pip3 install -r requirements.txt

jobs:
  include:
  - script: python3.6 setup.py install py2app && ditto -c -k --sequesterRsrc --keepParent dist/Better\ LES.app betterles.zip
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      file: betterles.zip
      draft: true
      on:
        tags: true
