#os: osx
#osx_image: xcode9.3
#language: python
#python: "3.6"
os: osx
language: generic

before_install:
- python3.6 --version
- curl -O https://bootstrap.pypa.io/get-pip.py
- python3 get-pip.py
- pip3 install -r requirements.txt

jobs:
  include:
  - script: python3.6 setup.py install py2app && cd dist && zip betterles Better\ LES.app
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      file: dist/betterles.zip
      draft: true
      on:
        tags: true
