#os: osx
#osx_image: xcode9.3
#language: python
#python: "3.6"

language: python

matrix:
  include:
  - os: osx
    language: generic
    env: TOXENV=py36

before_install:
- brew install python
- python --version
- pip install -r requirements.txt

jobs:
  include:
  - script: setup.py install py2app && cd dist && zip betterles Better\ LES.app
    deploy:
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      file: dist/betterles.zip
      draft: true
      on:
        tags: true
